all: max-io max-neg max-pos max-corr

max-io: 
	g++ max-io.cpp -o max-io

max-neg: 
	g++ max-neg.cpp -o max-neg

max-pos: 
	g++ max-pos.cpp -o max-pos


max-corr: 
	g++ max-corr.cpp -o max-corr	

clean :
	rm max-io max-neg max-pos max-corr